version: '3.5'
services:
  angular-service:
    container_name: nyc03
    build: .
    ports:
      - '4200:4200'
    command: >
      ng serve --proxy-config proxy.conf.json --host 0.0.0.0 --port 4200 --disable-host-check